### ISSUE TITLE
Project build fails with Template Render Error

### ISSUE THREAD

**Issue by CoolSpy3** [asyncapi/java-spring-template#108]
#### Describe the bug
Building [this project](https://github.com/bb-frc-workshops/wpilib-ws-schema) produces the following error:
```
Something went wrong:
Template render error: (node_modules\@asyncapi\generator\node_modules\@asyncapi\java-spring-template\template\src\main\java\com\asyncapi\model\$$objectSchema$$.java) [Line 135, Column 90]
  ReferenceError: obj is not defined
    at Object._prettifyError (node_modules\nunjucks\src\lib.js:36:11)
    at node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:1532:3)
    at Template.render (node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:550:10)
    at Environment.renderString (node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:378:17)
    at node-v14.15.3-win-x64\node-v14.15.3-win-x64\node_modules\@asyncapi\generator\lib\renderer\nunjucks.js:32:14
    at new Promise (<anonymous>)
    at nunjucksExport.renderNunjucks (node_modules\@asyncapi\generator\lib\renderer\nunjucks.js:31:10)
    at Generator.renderFile (node_modules\@asyncapi\generator\lib\generator.js:678:12)
    at async Generator.renderAndWriteToFile (node_modules\@asyncapi\generator\lib\generator.js:593:28)
    at async Generator.generateSeparateFile (node_modules\@asyncapi\generator\lib\generator.js:580:5)
    at async Promise.all (index 0)
    at async Generator.filesGenerationHandler (node_modules\@asyncapi\generator\lib\generator.js:508:9)
    at async Walker.<anonymous> (node_modules\@asyncapi\generator\lib\generator.js:442:11)
```
unless `java-spring-template` is downgraded to version 0.20.1.
#### How to Reproduce
1. Install AsyncAPI
2. Clone [this project](https://github.com/bb-frc-workshops/wpilib-ws-schema)
3. Run `npm install -g graceful-fs` to bypass issue #80 
4. Run `ag -o <dir> wpilib-ws-schema/schema/wpilib-ws.yaml @asyncapi/java-spring-template`
5. <Build Fails>
6. Run `ag -o <dir> wpilib-ws-schema/schema/wpilib-ws.yaml @asyncapi/java-spring-template@0.20.1`
7. <Build Succeeds>

#### Expected behavior
The code should build without errors on the latest version of `java-spring-template`

**Comment by derberg** [comment]
@CoolSpy3 I found the bug. I tested and your schema passes successfully with my change but I'm not able to say if the result is correct or not. Please check on your side, when you run `ag` just pass this as the template `https://github.com/derberg/java-spring-template/#fix-obj`

**Comment by CoolSpy3** [comment]
I can confirm that running that branch fixes the error. Thank you for your help :)

**Comment by derberg** [comment]
@CoolSpy3 awesome, I'll just grab a reviewer and we'll release it today
