### ISSUE TITLE
Error: Cannot find module 'graceful-fs' (GitBash / Win10)

### ISSUE THREAD

**Issue by whatthefrog** [asyncapi/java-spring-template#80]
#### Describe the bug

Following your README.md steps to use the `java-spring-template`, I got the below error :-( 

```
Something went wrong:
Error: Cannot find module 'graceful-fs'
```

Using GitBash on Windows 10

#### How to Reproduce

```
$ ag asyncapi.yaml @asyncapi/java-spring-template -o ./src
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi%2fjava-spring-template 3036ms
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi/java-spring-template/-/java-spring-template-0.19.0.tgz 3056ms
npm http fetch GET 304 https://registry.npmjs.org/tmp 238ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-extra 242ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/tmp/-/tmp-0.2.1.tgz 227ms
npm http fetch GET 200 https://registry.npmjs.org/fs-extra/-/fs-extra-9.0.1.tgz 258ms
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi%2fgenerator-filters 1016ms
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi/generator-filters/-/generator-filters-1.0.0.tgz 232ms
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi%2fgenerator-hooks 1792ms
npm http fetch GET 200 https://registry.npmjs.org/@asyncapi/generator-hooks/-/generator-hooks-0.1.0.tgz 223ms
npm http fetch GET 304 https://registry.npmjs.org/markdown-it 215ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/openapi-sampler 268ms
npm http fetch GET 200 https://registry.npmjs.org/openapi-sampler/-/openapi-sampler-1.0.0-beta.16.tgz 236ms
npm http fetch GET 200 https://registry.npmjs.org/markdown-it/-/markdown-it-10.0.0.tgz 376ms
npm http fetch GET 304 https://registry.npmjs.org/entities 202ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/json-pointer 202ms
npm http fetch GET 200 https://registry.npmjs.org/json-pointer/-/json-pointer-0.6.0.tgz 209ms
npm http fetch GET 200 https://registry.npmjs.org/foreach 229ms
npm http fetch GET 200 https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz 205ms
npm http fetch GET 304 https://registry.npmjs.org/jsonfile 203ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/graceful-fs 212ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/at-least-node 219ms
npm http fetch GET 304 https://registry.npmjs.org/universalify 223ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/jsonfile/-/jsonfile-6.0.1.tgz 207ms
npm http fetch GET 200 https://registry.npmjs.org/at-least-node/-/at-least-node-1.0.0.tgz 222ms
npm http fetch GET 200 https://registry.npmjs.org/universalify/-/universalify-1.0.0.tgz 219ms
npm http fetch GET 304 https://registry.npmjs.org/rimraf 213ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/glob 203ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inflight 225ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 228ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs.realpath 235ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/once 235ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/path-is-absolute 237ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wrappy 192ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fsevents 230ms (from cache)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @asyncapi/java-spring-template@0.19.0
added 22 packages from 13 contributors in 12.328s

14 packages are looking for funding
  run `npm fund` for details

Something went wrong:
Error: Cannot find module 'graceful-fs'
Require stack:
- C:\Users\johndoe\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\java-spring-template\node_modules\fs-extra\lib\fs\index.js
- C:\Users\johndoe\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\java-spring-template\node_modules\fs-extra\lib\index.js
- C:\Users\johndoe\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\java-spring-template\hooks\05_packageProcessor.js
- C:\Users\johndoe\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\hooksRegistry.js
- C:\Users\johndoe\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\generator.js
- C:\Users\johndoe\AppData\Roaming\npm\node_modules\@asyncapi\generator\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\johndoe\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\java-spring-template\node_modules\fs-extra\lib\fs\index.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\johndoe\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\java-spring-template\node_modules\fs-extra\lib\index.js:5:6)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

$ npm --version
6.14.6
```
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

#### Expected behavior

I had to `npm install -g graceful-fs` to solve this 

Did you forget to define this dependency ?

**Comment by derberg** [comment]
@whatthefrog hey, it is not a problem with this template but the generator. There is an issue about it here https://github.com/asyncapi/generator/issues/391

the problem is that it is not possible to reproduce on Mac and we are not yet sure how to fix it

**Comment by derberg** [comment]
looks like it is solved with https://github.com/asyncapi/java-spring-template/issues/108
Please reopen if I'm wrong
